insert into cars (mark, model, engine, fuel, price, image) values ('Lincoln', 'Town Car', 'V6', 'elekter', 850, '/massa/id/lobortis/convallis.html');
insert into cars (mark, model, engine, fuel, price, image) values ('Cadillac', 'Escalade EXT', 'V12', 'diisel', 112, '/quis.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Audi', 'A3', 'V12', 'gaas', 415, '/in/hac/habitasse/platea/dictumst/etiam.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Ford', 'Escape', 'V12', 'gaas', 587, '/sagittis/sapien/cum/sociis.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Mercedes-Benz', 'CL-Class', 'V12', 'diisel', 144, '/quam.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Ford', 'E-Series', 'V12', 'gaas', 545, '/a/libero.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Chevrolet', 'Malibu', 'V8', 'gaas', 325, '/auctor/gravida/sem/praesent.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Buick', 'Riviera', 'V8', 'gaas', 692, '/sit/amet/sapien/dignissim/vestibulum/vestibulum.jpg');
insert into cars (mark, model, engine, fuel, price, image) values ('Lexus', 'ES', 'V8', 'diisel', 544, '/vitae/nisl/aenean/lectus/pellentesque/eget/nunc.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Ford', 'Taurus', 'V12', 'diisel', 620, '/cursus/urna/ut/tellus.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Acura', 'TL', 'V12', 'bensiin', 558, '/quam/nec/dui/luctus/rutrum/nulla/tellus.jpg');
insert into cars (mark, model, engine, fuel, price, image) values ('Pontiac', 'Grand Prix', 'V6', 'gaas', 972, '/orci/luctus/et/ultrices/posuere.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Ford', 'Festiva', 'V12', 'bensiin', 539, '/odio.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Chevrolet', 'Cobalt', 'V12', 'diisel', 623, '/nec/nisi.js');
insert into cars (mark, model, engine, fuel, price, image) values ('Chevrolet', 'Metro', 'V12', 'bensiin', 388, '/pulvinar/lobortis/est/phasellus/sit/amet.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Porsche', 'Cayenne', 'V6', 'diisel', 647, '/vivamus.html');
insert into cars (mark, model, engine, fuel, price, image) values ('Mazda', 'MX-6', 'V8', 'elekter', 734, '/volutpat/in/congue/etiam/justo/etiam/pretium.json');
insert into cars (mark, model, engine, fuel, price, image) values ('GMC', 'Rally Wagon 2500', 'V6', 'diisel', 737, '/parturient/montes/nascetur/ridiculus.js');
insert into cars (mark, model, engine, fuel, price, image) values ('Chrysler', 'LHS', 'V8', 'diisel', 606, '/venenatis/tristique/fusce/congue.js');
insert into cars (mark, model, engine, fuel, price, image) values ('Mazda', 'Tribute', 'V12', 'elekter', 638, '/volutpat.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Audi', '4000s', 'V8', 'gaas', 649, '/vestibulum/sit/amet/cursus/id/turpis.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Subaru', 'Alcyone SVX', 'V12', 'diisel', 439, '/aenean/lectus/pellentesque/eget/nunc.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Honda', 'CR-V', 'V6', 'gaas', 570, '/quam/pharetra/magna/ac/consequat/metus/sapien.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('BMW', 'M6', 'V12', 'gaas', 585, '/interdum.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Mazda', 'MX-6', 'V8', 'diisel', 895, '/sit/amet/consectetuer/adipiscing/elit/proin/risus.jpg');
insert into cars (mark, model, engine, fuel, price, image) values ('Volkswagen', 'R32', 'V12', 'gaas', 435, '/et/ultrices/posuere.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Volkswagen', 'Corrado', 'V12', 'gaas', 629, '/eu/est/congue/elementum/in/hac/habitasse.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Lincoln', 'Continental Mark VII', 'V8', 'bensiin', 959, '/diam/in/magna.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Subaru', 'Legacy', 'V12', 'gaas', 600, '/turpis/integer/aliquet/massa.jpg');
insert into cars (mark, model, engine, fuel, price, image) values ('Mercedes-Benz', 'W126', 'V12', 'diisel', 423, '/posuere/cubilia/curae/mauris/viverra.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Pontiac', '1000', 'V12', 'gaas', 763, '/risus/dapibus.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Toyota', 'Tundra', 'V6', 'gaas', 418, '/nisl/nunc/nisl/duis/bibendum.png');
insert into cars (mark, model, engine, fuel, price, image) values ('GMC', 'Suburban 2500', 'V6', 'gaas', 878, '/est/quam/pharetra/magna/ac.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Ford', 'Mustang', 'V6', 'bensiin', 348, '/odio/elementum.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Nissan', 'Armada', 'V6', 'diisel', 907, '/justo/morbi/ut/odio/cras.js');
insert into cars (mark, model, engine, fuel, price, image) values ('Volvo', 'XC70', 'V8', 'gaas', 413, '/est/risus.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Pontiac', 'Grand Prix', 'V12', 'diisel', 125, '/blandit/non/interdum.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Kia', 'Sorento', 'V8', 'bensiin', 818, '/vivamus/metus/arcu.js');
insert into cars (mark, model, engine, fuel, price, image) values ('Mazda', 'B-Series Plus', 'V8', 'diisel', 496, '/vulputate/justo/in/blandit.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Toyota', '4Runner', 'V8', 'gaas', 769, '/nulla/ultrices/aliquet/maecenas/leo/odio.jpg');
